// hidden line generated by Node.js
// var exports = module.exports = {};

var Category = require('./model');
var _ = require('lodash');
var controller = {};

controller.params = function(req, res, next, id) {
    // use the id to find object from DB and attach to req
    Category
        .findById(id)
        .then(
            function(category){
                if(!category){
                    next(new Error('No category with id ' + id));
                }else{
                    req.category = category;
                    next();
                }
            }, 
            function(err){
                next(err);
            }
        );
};

controller.get = function(req, res, next) {
    Category
        .find({})
        .then(
            function(categories){
                res.json(categories);
            }, 
            function(err){
                next(err);
            }
        );
};

controller.getOne = function(req, res, next) {
    var category = req.category;
    res.json(category);
};

controller.put = function(req, res, next) {
    var curCategory = req.category;
    var newCategory = req.body;

    _.merge(curCategory, newCategory);

    curCategory.save(function(err, savedCat){
        if(err){
            next(err);
        }else{
            res.json(savedCat);
        }
    });
};

controller.post = function(req, res, next) {
    var newCategory = req.body;
    Category
        .create(newCategory)
        .then(
            function(category){
                res.json(category);
            }, 
            function(err){
                next(err);
            }
        );
};

controller.delete = function(req, res, next) {
    var category = req.category;
    category.remove(function(err, removedCat){
        if(err){
            next(err);
        }else{
            res.json(removedCat);
        }
    });
};

module.exports = controller;

/*
The alternative way to export stuffs

module.exports = {
    params : function(req, res, next, id) {    
    // use the id to find object from DB and attach to req
    Category
        .findById(id)
        .then(
            function(category){
                if(!category){
                    next(new Error('No category with id ' + id));
                }else{
                    req.category = category;
                    next();
                }
            }, 
            function(err){
                next(err);
            }
        );
    },

    get : function(req, res, next) {
    Category
        .find({})
        .then(
            function(categories){
                if(!categories) {
                    next(new Error(''));
                }
                else
                    res.json(categories);
            }, 
            function(err){
                next(err);
            }
        );
    }
};
*/